name: Ping Website and Notify

on:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes
  workflow_dispatch: # Allow manual triggering

jobs:
  ping_and_notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Ping website
      id: ping
      run: |
        response=$(curl -o /dev/null -s -w "%{http_code}\n" https://swiftdrones.net)
        echo "status=$response" >> $GITHUB_ENV

    - name: Check response and set failure
      if: env.status != '3030'
      run: |
        echo "The website is down."
        echo "::set-output name=status::failure"
      id: check_response

    - name: Send email if down
      if: steps.check_response.outputs.status == 'failure'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_PASSWORD }}
        subject: "Website Down Alert"
        body: |
          The website https://swiftdrones.net is down.
          Status code: ${{ env.status }}
        to: swiftdrones.contact@gmail.com
        from: ${{ secrets.GMAIL_USERNAME }}
